### ISSUE TITLE
Nothing Happens

### ISSUE THREAD

**Issue by Armin268** [MPh-py/MPh#108]
I tried to run the codes in Python but nothing happened?
Would you please help me in this regard?

![Screenshot 2023-01-21 133755](https://user-images.githubusercontent.com/122246737/213882145-68826e65-446f-4c71-910d-cc7babcdefc0.jpg)

**Comment by john-hen** [comment]
If you post images of your code, instead of text, I can't copy-and-paste the code and run it imyself. Which is really inconvenient. That being said, from the looks of it, and only that, that code shouldn't print anything to the console, unless there is an error. So if "nothing happens", that's a good thing. It means the code works as it's supposed to.

**Comment by Armin268** [comment]
Thank you so much for the answer.
It worked.
