### ISSUE TITLE
Complex numbers in parameter assignments

### ISSUE THREAD

**Issue by ssackMWL** [MPh-py/MPh#36]
There seems to be a problem with complex-valued parameters. If I call:

` model.parameter("x", 1+1j)

in version 1.0.0 with Comsol 5.6 I get the following error:

> Traceback (most recent call last):
>   File "xyz", line 73, in <module>
>     model.parameter("x", 1+1j)
>   File "C:\Python37\lib\site-packages\mph\model.py", line 583, in parameter
>     self.java.param().set(name, value)
> TypeError: can't convert complex to float
>

**Comment by John-Hennig** [comment]
Thanks for reporting. So this happens because [as of version 1.0](https://mph.readthedocs.io/en/latest/api/mph.Model.html#mph.Model.parameter) numerical values in parameter assignments are no longer implicitly converted to strings, as they were [in version 0.8](https://mph.readthedocs.io/en/0.8/api/mph.Model.html#mph.Model.parameter) for example.

The reason for the change is that the Comsol API often accepts the numerical values directly (via an "overloaded" method), so we wouldn't want to interpose a string conversion that's not strictly necessary. Especially because the `.parameter()` method may also return the numerical values directly (if the `evaluate` option is set to `True`), so it's best to pass in what we expect to come out.

However, while this works for (real-valued) floating-point numbers, or integer numbers for that matter, it doesn't seem to work for complex numbers. I'll see if that's possible and add it to the type-casting mechanism if it is. Otherwise I can also re-introduce the implicit string conversion if `value` is a complex number.

In the meantime, you can just do the string conversion explicitly. So just `model.parameter('x', '1+1j')` if  `1+1j` is the expression you'd enter in the Comsol GUI. (I haven't tested it, but it must be, otherwise the conversion would not have worked in earlier releases.) Or if, in your code, you have the value stored as a variable, say `z`, you'd pass `str(z)`.

**Comment by John-Hennig** [comment]
Fixed in version 1.0.1.
