### ISSUE TITLE
Export of animations

### ISSUE THREAD

**Issue by EmirChacra** [MPh-py/MPh#43]
Hi,

Currently, exporting animations specifying the filename is not working, mainly because animation don't use "filename" as a property, but different ones depending on the file type used.

I made a little workaround for my case. I'm exporting not animations but image sequences so i can load them later, so i modified very naively the export function so it can treat my accordingly. Here is the code so it can work as an inspiration hahaha

`def export(self, node=None, file=None, anim = False):`

        if node is None:
            for node in self/'exports':
                logger.info(f'Running export node "{node.name()}".')
                node.run()
                logger.info('Finished running export.')
        else:
            if isinstance(node, str):
                if '/' in node:
                    node = self/node
                else:
                    node = self/'exports'/node
            if not node.exists():
                error = f'Node "{node}" does not exist in model tree.'
                logger.error(error)
                raise ValueError(error)
            if file and anim:
                node.property('imagefilename', str(file))
            else:
                node.property('filename', str(file))
            logger.info(f'Running export node "{node.name()}".')
            node.run()
            logger.info('Finished running export.')

other filenames used by animation are "giffilename", "avifilename", "flashfilename", so there must by a way to tell the function which to use.

Cheers!

**Comment by John-Hennig** [comment]
Thanks for reporting this. I will file this as a bug since, technically, the [`export()`](https://mph.readthedocs.io/en/1.0/api/mph.Model.html#mph.Model.export) method does not work as one might think if the export node defines an animation and a `file` argument is passed.

Though another way to achieve the same outcome should be to [set the property](https://mph.readthedocs.io/en/1.0/api/mph.Node.html#mph.Node.property) "imagefilename" (or whichever property name may apply) of a given export node and then just [run the node](https://mph.readthedocs.io/en/1.0/api/mph.Node.html#mph.Node.run). (I have not tested this, I'm basing this on your description.)

I will look into supporting animations in `Model.export()`. I am generally reluctant to introduce new arguments (such as `anim` here), but that's just to keep the API as clean as possible. Maybe the choice of the property name can just depend on the file extension. It's not entirely clear to me yet if that's possible. Like, it should be possible for `.gif`, `.avi`, and `.flv`, but not sure what `file` would be for the image sequence that you exported.

**Comment by max3-2** [comment]
I took a fairly quick look and I think this could get complicated - one of those cases where the COMSOL API is just very ambiguous. I use the demo model and added a quick Animation export using the GUI. Then: 

`(m/'exports/data').properties()` has
```
filename
```,
`(m/'exports/image').properties()` has
```
bmpfilename,
epsfilename,
giffilename,
gltffilename,
jpegfilename,
pngfilename,
tifffilename,
```
and lastly `(m/'exports/Animation 1').properties()` has
```
avifilename,
flashfilename,
giffilename,
imagefilename,
webmfilename
```

In a first step, we could distinguish the nodes for image and animation data via the implemented `type`, e.g.
```python
In [20]: (m/'exports/image').type()
Out[20]: 'Image'

In [21]: (m/'exports/data').type()
Out[21]: 'Data'

In [22]: (m/'exports/Animation 1').type()
Out[22]: 'Animation'
```

Using this and the supplied suffix, we could run a check if the suffix is valid for the type of export and if yes, set the right `filename`. For `Data` exports, I would leave that completely free since the possibilities are endless there.
Going this way obviously has the risk that many more exceptions will occur with other node types and the code will increase in complexity. Another way would be simply catching the exception with a hint to the user that in the case of those *sepcial* exports one has to set the right property himself.

**Comment by john-hen** [comment]
Added in MPh 1.1.3, released today.
