### ISSUE TITLE
Geometry position Base option

### ISSUE THREAD

**Issue by vegaonline** [MPh-py/MPh#44]
I wished to put my query as chat instead of issue of this superb software while I could not do that. I apologize if my post is a bad post.

I wanted to transfer my transmon qubit geometry developed in python into comsol for modal EM simulation. While designing the aluminium layer (CPW) on the sapphire  substrate, I found that I coudl not position the geometry with comsol position/base/center option. I could not find equivalent option in java.

Also I found that if I have another issue. If I have any issue in geometry or other parts,   I need to restart from importing of modules. Is there any shortcut to delete model and restart from model definition subpart e.g. start from Model geometry?

I am using Ubuntu 20.04

**Comment by vegaonline** [comment]
Well, just now I have found that <geometry name>.property('base','center') works properly.
e.g.
enclosure = geometry.create('Block', name='enclosure')
enclosure.property('base','center')

**Comment by John-Hennig** [comment]
Sorry for the late reply. It seems that you solved your problem and this issue can be closed?

Generally speaking, I can offer little help with such specific problems. All I can say is, if it can be done in Java, it can also be done in Python. And vice versa: If it cannot be done in Java, then it can't be done in Python either. MPh is just a Python wrapper, its purpose is to automate the simulation workflow so that custom post-processing can seamlessly leverage Python's scientific stack.

**Comment by vegaonline** [comment]
This code is really great and thanks for kindly placing it on github. It can be closed.
