### ISSUE TITLE
Exporting meshes as `.mphtxt` files

### ISSUE THREAD

**Issue by banduser** [MPh-py/MPh#73]
Hi,

Im currently writing a Python optimization script with which I want to vary geometric parametrs of a Comsol model using MPh and create and export Meshes of the Model. 

Since I'm not running any actual Simulations on the Model and only want the Mesh, my only export Node is a Mesh export Node. With this export node I want to generate an .mphtxt file of my model. However, when I attempt to run the code I get the following error message:

TypeError: Node "exports/Mesh 1" is of the unexpected type "Mesh".

Is the exporting of Meshes not implmented or am I simply overlooking something? Attached are screenshots of my code.

Thanks in advance!
![mph code](https://user-images.githubusercontent.com/101814714/158833682-1fa9d88a-1dd5-40cb-afe1-4bbfa1172479.PNG)
![mph](https://user-images.githubusercontent.com/101814714/158833689-c27fb971-73c7-4233-83fc-246ea35a0690.PNG)

**Comment by john-hen** [comment]
Hi. Yeah, looks like it's not implemented. I did not even know there are export nodes for meshes.

By "not implemented" I mean that MPh's [`Model.export()`](https://mph.readthedocs.io/en/1.1/api/mph.Model.html#mph.Model.export) method is just as unaware of it as I am. Obviously, if it can be done in Java, then it can be done in Python. So there's definitely a way to do it.

**Comment by banduser** [comment]
Thanks John! Any chance of this being implemented in the near future? If not, is there a workaround I could use in the meantime?

**Comment by john-hen** [comment]
Yeah, I'll fix that eventually. Unless you want to contribute a pull request?

The work-around is to use (what I call) the "Java layer" directly, instead of the high-level functions of MPh's API. This is what's explained in section ["Access the full Comsol API"](https://mph.readthedocs.io/en/1.1/demonstrations.html#access-the-full-comsol-api).

So, whenever some functionality is missing, open your model in the Comsol GUI, perform whatever action you want to automate (here: export the mesh), then save the model as a `.java` file, and look at the Java code. The lines you're interested in will be at the very end. (It may help to "Compact History" before saving, which removes redundant code lines from the Java code.) Then translate that Java code to Python. That usually just means replacing `model.` with `model.java` at the start of the line.

**Comment by john-hen** [comment]
Fixed in MPh 1.1.6, released today.
